name: curator_cli publish
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'curator-cli/**'

jobs:
  Publish-curator_cli-Package:
    runs-on: windows-latest
    steps:
      - run: echo 'The triggering workflow passed'
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: ğŸ“¦ Pack Chocolatey Package
        run: choco pack curator-cli/curator-cli.nuspec
      - name: ğŸ” Set Chocolatey API-KEY
        run: choco apikey --api-key ${{ secrets.API_KEY }} -source https://push.chocolatey.org/
      - name: ğŸš€ Push Chocolatey Package
        run: choco push -source https://push.chocolatey.org/
